/* eslint-disable react-refresh/only-export-components */
export * from "./pokemonGens/pokemonGen1/Pokemon";
export * from "./pokemonGens/pokemonGen2/Pokemon";
export * from "./pokemonGens/pokemonGen3/Pokemon";
export * from "./pokemonGens/pokemonGen4/Pokemon";
export * from "./pokemonGens/pokemonGen5/Pokemon";
export * from "./pokemonGens/pokemonGen6/Pokemon";
export * from "./pokemonGens/pokemonGen7/Pokemon";
export * from "./pokemonGens/pokemonGen8/Pokemon";
export * from "./pokemonGens/pokemonGen9/Pokemon";
