/* eslint-disable react-refresh/only-export-components */
export * from "./pokemonGens/Gen1/Pokemon";
export * from "./pokemonGens/Gen2/Pokemon";
export * from "./pokemonGens/Gen3/Pokemon";
export * from "./pokemonGens/Gen4/Pokemon";
export * from "./pokemonGens/Gen5/Pokemon";
export * from "./pokemonGens/Gen6/Pokemon";
export * from "./pokemonGens/Gen7/Pokemon";
export * from "./pokemonGens/Gen8/Pokemon";
export * from "./pokemonGens/Gen9/Pokemon";
